---
# tasks file for monit
 - name: install epel-release 
   yum:
    name: epel-release
    state: latest
 
 - name: update the cache and exclude kernel
   yum:
    name: '*'
    state: present 
    exclude: kernel*
  
 - name: install monit
   yum:
    name: monit
    state: latest  
 
 - name: copy monitrc file from controller with node ip.
   template:
    src: monitrc
    dest: /etc/monitrc
   notify:
    - restart monit
 
 - name: add service file to the /etc/monit.d/ directory  
   copy:
    src: "{{ item }}"
    dest: /etc/monit.d/
   with_fileglob:
    - "{{user_home}}/monit/files/*" 
   notify:
    - reload monit 
 
